# Generated by Django 4.0.2 on 2022-03-06 07:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CovidData',
            fields=[
                ('s_no', models.IntegerField(primary_key=True, serialize=False)),
                ('observation_date', models.DateField()),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(max_length=200)),
                ('last_update', models.DateTimeField()),
                ('confirmed', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('deaths', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('recovered', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
